#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lualgi
Version  : 0.9.2
Release  : 3
URL      : https://github.com/pavouk/lgi/archive/0.9.2.tar.gz
Source0  : https://github.com/pavouk/lgi/archive/0.9.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: lualgi-data = %{version}-%{release}
Requires: lualgi-lib = %{version}-%{release}
Requires: lualgi-license = %{version}-%{release}
BuildRequires : gobject-introspection-dev
BuildRequires : lua-dev
Patch1: deal-with-hardcoded-path.patch

%description
# LGI
LGI is gobject-introspection based dynamic Lua binding to GObject
based libraries.  It allows using GObject-based libraries directly
from Lua.

%package data
Summary: data components for the lualgi package.
Group: Data

%description data
data components for the lualgi package.


%package lib
Summary: lib components for the lualgi package.
Group: Libraries
Requires: lualgi-data = %{version}-%{release}
Requires: lualgi-license = %{version}-%{release}

%description lib
lib components for the lualgi package.


%package license
Summary: license components for the lualgi package.
Group: Default

%description license
license components for the lualgi package.


%prep
%setup -q -n lgi-0.9.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540942328
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1540942328
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lualgi
cp LICENSE %{buildroot}/usr/share/package-licenses/lualgi/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/lua/5.3/lgi.lua
/usr/share/lua/5.3/lgi/class.lua
/usr/share/lua/5.3/lgi/component.lua
/usr/share/lua/5.3/lgi/core.lua
/usr/share/lua/5.3/lgi/enum.lua
/usr/share/lua/5.3/lgi/ffi.lua
/usr/share/lua/5.3/lgi/init.lua
/usr/share/lua/5.3/lgi/log.lua
/usr/share/lua/5.3/lgi/namespace.lua
/usr/share/lua/5.3/lgi/override/Clutter.lua
/usr/share/lua/5.3/lgi/override/GLib-Bytes.lua
/usr/share/lua/5.3/lgi/override/GLib-Error.lua
/usr/share/lua/5.3/lgi/override/GLib-Markup.lua
/usr/share/lua/5.3/lgi/override/GLib-Source.lua
/usr/share/lua/5.3/lgi/override/GLib-Timer.lua
/usr/share/lua/5.3/lgi/override/GLib-Variant.lua
/usr/share/lua/5.3/lgi/override/GLib.lua
/usr/share/lua/5.3/lgi/override/GObject-Closure.lua
/usr/share/lua/5.3/lgi/override/GObject-Object.lua
/usr/share/lua/5.3/lgi/override/GObject-Type.lua
/usr/share/lua/5.3/lgi/override/GObject-Value.lua
/usr/share/lua/5.3/lgi/override/Gdk.lua
/usr/share/lua/5.3/lgi/override/Gio-DBus.lua
/usr/share/lua/5.3/lgi/override/Gio.lua
/usr/share/lua/5.3/lgi/override/GooCanvas.lua
/usr/share/lua/5.3/lgi/override/Gst.lua
/usr/share/lua/5.3/lgi/override/Gtk.lua
/usr/share/lua/5.3/lgi/override/Pango.lua
/usr/share/lua/5.3/lgi/override/PangoCairo.lua
/usr/share/lua/5.3/lgi/override/cairo.lua
/usr/share/lua/5.3/lgi/package.lua
/usr/share/lua/5.3/lgi/record.lua
/usr/share/lua/5.3/lgi/version.lua

%files lib
%defattr(-,root,root,-)
/usr/lib/lua/5.3/lgi/corelgilua51.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lualgi/LICENSE
